import type { Lot } from "./types";

export const sampleLots: Lot[] = [
  {
    id: "rosan-104",
    source: "rosan-reeves",
    auctionHouse: "Rosan Reeves",
    auctionTitle: "235 lots located at Hailsham",
    lotNumber: 104,
    title: "Canon T90 with Canon FD 15mm f/2.8 fisheye",
    description: "Canon T90 35mm SLR camera with rare Canon FD 15mm f/2.8 fisheye lens and handbook.",
    conditionReport: "Camera untested. Lens appears clear with no obvious heavy scratching or fungus.",
    imageUrls: [],
    currentBid: null,
    startPrice: 10,
    estimatedResaleLow: 480,
    estimatedResale: 600,
    estimatedResaleHigh: 720,
    maxHammerBid: 261,
    expectedProfit: 180,
    confidence: "High",
    recommendation: "BUY",
    closingAt: "2026-07-19T18:00:00+01:00",
    url: "https://bid.rosanreevesauctions.co.uk/auction/234-235-lots-located/lot-104-canon-t90/"
  },
  {
    id: "rosan-180",
    source: "rosan-reeves",
    auctionHouse: "Rosan Reeves",
    auctionTitle: "235 lots located at Hailsham",
    lotNumber: 180,
    title: "PS5 Slim Digital with two DualSense controllers",
    description: "PlayStation 5 Slim Digital Edition with two controllers and charging dock.",
    conditionReport: "Untested auction condition. Check controller drift, HDMI output and storage.",
    imageUrls: [],
    currentBid: null,
    startPrice: 10,
    estimatedResaleLow: 285,
    estimatedResale: 325,
    estimatedResaleHigh: 360,
    maxHammerBid: 137,
    expectedProfit: 98,
    confidence: "High",
    recommendation: "BUY",
    closingAt: "2026-07-19T18:00:00+01:00",
    url: "https://bid.rosanreevesauctions.co.uk/auction/234-235-lots-located/lot-180-sony-playstation/"
  },
  {
    id: "rosan-216",
    source: "rosan-reeves",
    auctionHouse: "Rosan Reeves",
    auctionTitle: "235 lots located at Hailsham",
    lotNumber: 216,
    title: "PS5 Disc Edition with two DualSense controllers",
    description: "PlayStation 5 Disc Edition bundle with two controllers.",
    conditionReport: "Untested. Confirm disc drive, controller condition and all leads.",
    imageUrls: [],
    currentBid: null,
    startPrice: 10,
    estimatedResaleLow: 260,
    estimatedResale: 295,
    estimatedResaleHigh: 340,
    maxHammerBid: 124,
    expectedProfit: 89,
    confidence: "High",
    recommendation: "BUY",
    closingAt: "2026-07-19T18:00:00+01:00",
    url: "https://bid.rosanreevesauctions.co.uk/auction/234-235-lots-located/lot-216-a-carton/"
  },
  {
    id: "rosan-165",
    source: "rosan-reeves",
    auctionHouse: "Rosan Reeves",
    auctionTitle: "235 lots located at Hailsham",
    lotNumber: 165,
    title: "Five Tamiya 1:12 Formula 1 model kits",
    description: "Collection of five large-scale Tamiya Formula 1 plastic model kits.",
    conditionReport: "Value depends on exact models, sealed bags, instructions, decals and completeness.",
    imageUrls: [],
    currentBid: null,
    startPrice: 10,
    estimatedResaleLow: 350,
    estimatedResale: 450,
    estimatedResaleHigh: 575,
    maxHammerBid: 188,
    expectedProfit: 135,
    confidence: "Medium",
    recommendation: "WATCH",
    closingAt: "2026-07-19T18:00:00+01:00",
    url: "https://bid.rosanreevesauctions.co.uk/auction/234-235-lots-located/lot-165-a-collection-2/"
  },
  {
    id: "rosan-1",
    source: "rosan-reeves",
    auctionHouse: "Rosan Reeves",
    auctionTitle: "235 lots located at Hailsham",
    lotNumber: 1,
    title: "Custom gaming PC with RTX 3070 Vision OC",
    description: "Custom PC containing a Gigabyte RTX 3070 Vision OC graphics card.",
    conditionReport: "Whole-system value depends on CPU, RAM, storage and whether it boots and passes stress tests.",
    imageUrls: [],
    currentBid: null,
    startPrice: 10,
    estimatedResaleLow: 380,
    estimatedResale: 450,
    estimatedResaleHigh: 550,
    maxHammerBid: 188,
    expectedProfit: 135,
    confidence: "Medium",
    recommendation: "WATCH",
    closingAt: "2026-07-19T18:00:00+01:00",
    url: "https://bid.rosanreevesauctions.co.uk/auction/234-235-lots-located/lot-1-custom-gaming/"
  }
];
